- lib/slack/state.ex
I'm not sure this is correct, but it compiles now at least. I was getting 
```
atom cannot be followed by an alias. If the '.' was meant to be part of the atom's name, the name must be quoted. Syntax error before: '.'
```
> Attempt to fix syntax error

- lib/slack/socket.ex
- test/slack/socket_test.exs
This fixes #2. Was there a variable name change from handler_state to module_state? I have tested this in a live slack implementation and it works for me.
> Fixes State not persisting

- README.md
The Readme contains an outdated example using `send` instead of `send_message`. I've also remove the websocket snippet that was floating in the readme without any explanation or context given.
> Correct code example (use send_message), remove websocket snippet.

- lib/slack.ex
- test/slack_test.exs
This commit enables `Slack.send_ping`, which can be handled via the existing `Slack.handle_message`.
It's more involved than it ought to be for 2 reasons:
- Passing the client in to each `send_x` was showing unnecessary duplication. 
The [first commit](https://github.com/BlakeWilliams/Elixir-Slack/commit/a5bdd153310f886d36460323ac9dca816dafed55) refactors this parameter into the `slack` map. 
As I'm not clear on the usecase of changing which client is used per call, I've moved it into an `init` parameter, which makes just as much sense to me given my usecase-unenlightened perspective. This change can be reverted if need be.
- I discovered an odd null-byte padding issue with some message responses.
The [last commit](https://github.com/BlakeWilliams/Elixir-Slack/commit/2da3367c2013c24c4b3f64 …
> Allow clients to send pings

- lib/slack/handlers.ex
Easy enough--"type" was unused, and Elixir complained.
> Fix a compiler warning in handlers.ex

- .travis.yml
- README.md
- Add travis CI to run tests against builds.
- Add build status indicator to README.
This resolves issue (https://github.com/BlakeWilliams/Elixir-Slack/issues/21)
Only thing required by repository owner is to.. 
- Goto https://travis-ci.org and sign in with github.
- Visit the page https://travis-ci.org/profile/BlakeWilliams
- Enable Travis CI for the repo `BlakeWilliams/Elixir-Slack`
This is free to use for public repos so there is no cost.  
Please look at https://github.com/afaur/Elixir-Slack for an example of the status indicator working after enabling it on travis-ci.org.  If you look you should see the Build Status as failing since I made some tests fail and pushed the changes into my master branch of my fork of this repo.  
Those tests are not altered in this PR so everything …
> Add TravisCI for build testing

- .travis.yml
Looks like this repo may not be set up to run on travis as of yet.
Here are the instructions for setting your repo to be monitored.
- Goto https://travis-ci.org and sign in with github.
- Visit the page https://travis-ci.org/profile/BlakeWilliams
- Enable Travis CI for the repo `BlakeWilliams/Elixir-Slack`
If you already completed these tasks let me know..  
I tested this on my fork and everything seems to be working correctly for me.
(The Travis badge at the top of the readme is passing here: https://github.com/afaur/Elixir-Slack)
> Test travis is working.

- mix.lock
Elixir forces using https now. Users of this project will get an unchecked dependency, which can only be resolved with `override: true` in their mix.exs file.
This PR was created by running `mix deps.get` in this project. It was not changed manually.
> Update to https for deps

- lib/slack.ex
Currently the only defined `websocket_info/3` is [here](https://github.com/BlakeWilliams/Elixir-Slack/blob/master/lib/slack.ex#L104) and so sending any other message to the slack process results in termination of the slack bot since no pattern matches in `websocket_info/3` (which was kind of hard to debug).
This PR adds `handle_info/3` so that all other messages can be handled by the client who does `use Slack`. This is useful for example when passing off a user and message to be posted (that another process generated), like `send(:slack, {user, messge})` (assuming `:slack` is a registered pid that has `use Slack`) and letting the slack process manage all communication to users.
> Add handle_info/3

- mix.exs
Without this, the application dies with `undef JSX.decode!`.
The fix is described here: https://hexdocs.pm/exrm/extra-common-issues.html
Quoting the page:
Ensure all dependencies for your application are defined in either the `:applications` or `:included_applications` block of your `mix.exs` file. This is how the build process knows that those dependencies need to be bundled in to the release. **This includes dependencies of your dependencies, if they were not properly configured**. For instance, if you depend on `mongoex`, and `mongoex` depends on `erlang-mongodb`, but `mongoex` doesn’t have `erlang-mongodb` in it’s applications list, your app will fail in it’s release form, because `erlang-mongodb` won’t be loaded.
> Fixes mix release deployment

- lib/slack.ex
This fixes an issue I was having with implementing `handle_info`.
If I returned new state from my `handle_info` function, the state wasn't being updated. I noticed that in the current implementation of `websocket_info`, there wasn't anything being done with the return value.
> Fix state returned from handle_info

- lib/slack/handlers.ex
- test/slack/handlers_test.exs
So it would appear that the members section is blank before joining a channel so if the bot joins the channel after being started it won't have anything in the `members` key. This appears to fix the problem by just making sure the `members` key is replaced with the latest `members` `channel_joined`.
> Ensure members is updated when joining a channel

- lib/slack/handlers.ex
- test/slack/handlers_test.exs
It would appear a simple typo in the test description meant that this
bug was not made apparent. I ran into this while making my other PR
relating to the channel_joined event.
> Fix the channel_left handler

- README.md
Unless I'm missing something it would appear that `init` is not exposed by the `Slack` module but rather it would appear that `handle_connect` is the correct way to hook into a startup callback.
> Update README.md with handle_connect

- lib/slack/handlers.ex
- test/slack/handlers_test.exs
In the current implementation our local `slack` cache is out of date if other people leave or join a channel we are in. According to the slack documentation for [channel_join](https://api.slack.com/events/message/channel_join) and [channel_leave](https://api.slack.com/events/message/channel_leave) we will get a message with these subtypes whenever somebody else joins or leaves a channel that we're in. It would seem then that we should add/remove those members from the slack cache under those circumstances.
Let me know if you think this doesn't make sense or could be simplified. Thanks for the speedy merges on our other PRs.
> handle channel_join and channel_leave events, update members

- lib/slack.ex
I'm not 100% sure this is the desired behavior for all use cases but for us at least this is what we want. The main reason this is necessary is that when we receive `:channel_joined` events we are joining a channel for the first time which means we don't have the `members`. If we don't call `handle_slack` first then the `members` key is empty and our `channel_joined` handler doesn't have access to that vital piece of information.
> Update slack state before forwarding messages

- lib/slack/handlers.ex
- test/slack/handlers_test.exs
Previously, interacting with private groups would fail; Slack does not
have a `group_created` event to parallel its `channel_created` event,
and so the code would crash trying to update data nested under `nil`
whenever a `group_joined` event came in.
To address this, the previously common implementation for channel and
group event handling was split to the extent necessary for dealing with
group interactions. When receiving a `group_joined` event, we simply add
the group map to the `slack` object. There is no reason to keep track of
an `is_member` key, since the user must be a member of the group by
definition.
Users joining and leaving a group is also handled. It turns out that
both a `group_joined` event as well as a `group_join` message are
received, so we ensure that the list of …
> Handle group interactions

- lib/slack/handlers.ex
Fix this warning
```
==> slack
Compiled lib/slack/rtm.ex
Compiled lib/slack.ex
lib/slack/handlers.ex:15: warning: variable x is unused
Compiled lib/slack/handlers.ex
Generated slack app
```
> Fix an unused variable warning

- lib/slack/handlers.ex
- test/slack/handlers_test.exs
It would appear from the
[docs](https://api.slack.com/events/channel_left) and local testing that
slack is only giving the id of the channel for channel_left events.
Funnily enough I just submitted PR #40 that changed this the other way
around before, but it is for some reason broken. That might have been an
oversight from before.
> Fix channel_left handler

- lib/slack/handlers.ex
- test/slack/handlers_test.exs
If we don't process presence_changed messages, slack.users[user].presence ends up being wrong
> Make presence change messages update presence in slack.users

- README.md
- lib/slack.ex
- lib/slack/handlers.ex
- lib/slack/lookups.ex
- lib/slack/sends.ex
- test/slack/handlers_test.exs
- test/slack/lookups_test.exs
- test/slack/sends_test.exs
- test/slack_test.exs
The main change here is that `Slack.send_message/2` is enhanced to understand calls in these formats:
* `Slack.send_message("whatever", "#some_channel")`
* `Slack.send_message("whatever", "@some_user")`
The latter sends a direct message to a user.  If you have never communicated with them privately before, a separate call is made to the Slack Web API to open a channel and then the message is sent.  Bots now track these direct message channels as part of their state.
Convenience functions were also added to lookup names and identifiers.
**Potential problems with my changes**:
My new code should not effect existing code.  You have to use these new features to be affected by the changes.
My name lookup strategy isn't ideal since it scans through `Map` values.  This probably isn't slow enough …
> Support Sending Messages to Channels and Users by Name

- README.md
- lib/slack.ex
- lib/slack/handlers.ex
- test/slack/handlers_test.exs
- test/slack_test.exs
Managing state for the user adds a good amount of complication to the
library in terms of maintaining and writing bots. This removes the state
management from Slack in favor of bot writers managing it themselves.
eg: The `Agent` module.
> Remove state management from Slack

- README.md
PR for issue discussed at: https://github.com/BlakeWilliams/Elixir-Slack/issues/71
Fixes the example for sending a message to a channel by name.
> Clarified channel hash requirement in examples

- lib/slack.ex
- lib/slack/rtm.ex
Fixes #45.
Took me about 30 requests to connect in a second to trigger, but now it won't let me make more than one a second, which is what the docs claim is the hard cap--so I guess they're pretty forgiving!
> Handles general json parse errors and special throttled case.

- lib/slack/web/documentation.ex
In the Slack documentation required documentation is specified by a
`required` key in the argument object in the json. Some fields don't
have the key and are ignored since the code was looking for `true` or
`false`.
This fixes the documentation bug by checking for truthy, or non-truthy
values.
This also adds the example to each param description when applicable.
> Fix ignored docs because of missing required key

- README.md
- lib/slack.ex
- lib/slack/bot.ex
- lib/slack/sends.ex
- lib/slack/state.ex
- mix.exs
- mix.lock
- test/bot_test.exs
- test/slack/sends_test.exs
- test/slack_test.exs
This changes a non-trivial amount of details about the implementation some
of which affect the public API.
* Uses hex hosted `websocket_client` which has a slightly improved API
and removes the need to add the github dependency when using this lib
* Re-introduces state per bot which means `handle_*` functions now
receive the state as an argument
* `start_link` now takes `initial_state` before the token
> Use bots through module function calls

- README.md
- lib/slack.ex
- lib/slack/bot.ex
The rename makes more sense because the "message" received might not be
a message.
> Rename handle_message to handle_event

- lib/slack/bot.ex
Fixes https://github.com/BlakeWilliams/Elixir-Slack/issues/90 by removing the `:type` check.
> Proxy all internal messages to the bot handler.  Fixes #90

- .travis.yml
- lib/mix/tasks/update_slack_api.ex
- lib/slack/sends.ex
- lib/slack/web/documentation.ex
- mix.exs
- test/slack/sends_test.exs
- test/slack/state_test.exs
- test/slack/web/documentation_test.exs
`Slack.Web.Chat.post_message/3` does not work when upgrading elixir to 1.4. Here is the error we get:
```elixir
iex(1)> Slack.Web.Chat.post_message("test_channel", "hello")
** (ArgumentError) expected a keyword list as the second argument, got: [{"text", "hello"}, {"channel", "test_channel"}]
(elixir) lib/keyword.ex:589: Keyword.merge/2
(slack) lib/slack/web/web.ex:44: Slack.Web.Chat.post_message/3
```
This is happening because of https://github.com/elixir-lang/elixir/pull/5466. 
In
```elixir
params = optional_params
|> Map.to_list
|> Keyword.merge(required_params)
|> Keyword.put_new(:token, Application.get_env(:slack, :api_token))
```
`required_params` passed to `Keyword.merge` is not a `Keyword` and because of the latest changes in Elixir, `Keyword.merge` will raise error if passed …
> Fix issues with post_message on Elixir 1.4

- .travis.yml
- lib/slack/sends.ex
- lib/slack/state.ex
- test/slack/sends_test.exs
Why:
* Nullary functions without parenthesis cause warnings.
* Access behaviour warns about missing get and pop functions.
* Dict.merge/2 is deprecated.
This change addresses the need by:
* Add parenthesis to nullary functions.
* Delegate get and pop to Map for Slack.State.
* Refactor Slack.Sends.send_ping/2 to use Map.merge/2 instead of
Dict.merge/2.
Side effects:
* There should be no side effects.
> Fix warnings for Elixir v1.4.0.

- lib/slack/lookups.ex
- test/slack/lookups_test.exs
You can now Lookups.lookup_channel_id for a private channel
and receive a "Gxxx" group identifier
and Lookups.lookup_channel_name for a private channel and
receive the name
fixes #105
> Private channel lookup

- .travis.yml
- lib/slack/rtm.ex
The slack API provides a key for checking if the response was successful for not. This PR adds a check for `ok: true` in the API response
> Handle RTM failure scenario

- lib/slack/web/web.ex
Now same `params` function is generated for each function.
> Generate helper functions once per module

- lib/slack/web/web.ex
When calling `Slack.Web.Oauth.access/3`, a `nil` token is used causing the Oauth flow to fail with an `invalid_auth` error. Removing `nil` valued keywords fixes the issue.
> Remove `nil` valued keywords from params

- lib/slack/web/web.ex
Compiler was warning about `k` being unused
> Remove unused variable

- lib/slack/bot.ex
Fixes #120.
Add ondisconnect function head that matches keepalive timeout
and reconnects rather than crashing. Retain original behavior for
all other disconnect reasons.
> Handle websocket keepalive timeout with reconnect

- lib/slack/sends.ex
- test/slack/sends_test.exs
I ran in to an issue in my app where I was trying to use `send_message/3` with a slack user ID and was getting silent failures. I dug around the source and realized I need to use `@user_name` instead. I had to dig around a bit to discover the `Slack.Lookups` module and use something like `user = Slack.Lookups.lookup_user_name(user_id, slack)` to send a messages. I ran in to this because my app is storing slack user IDs and *initiating* conversations, so I'm not just responding to inbound message where the user name / channel is already present.
> Allow send_message/3 to accept a user ID

- lib/slack/state.ex
- test/slack/state_test.exs
The `user_change` event does not include presence data, so if we just
replace the user in `slack.users`, then we lose any presence data we've
stored for that user.
Also updates a test where we were testing the wrong message type.
> Don't discard presence data when a user is changed

- lib/slack/rtm.ex
- lib/slack/sends.ex
- lib/slack/state.ex
- test/slack/sends_test.exs
- test/slack/state_test.exs
Presence change tracking has changed in slack (see
https://api.slack.com/docs/presence-and-status#batching)
This change updates us to tell slack that we understand the new
presence processing messages, and updates us to handle them properly.
Presence data will still not be supplied to clients until the client
subscribes to presence notifications, so this change also adds a
function to make that a bit more convenient.
> Update to deal with changed presence tracking.

- lib/slack/state.ex
- test/slack/state_test.exs
I have hit several crashes in my slack application upon processing a `user_change` message. Upon further inspection, it is because there is no existing user in the state map when the message is processed. 
That is to say,
slac.users[user.id] is null, so Map.merge(null, %{}) returns a badmap exception.
This PR fixes this case by defaulting the user to the empty map when merging in the new state. I have added tests for this case as well.
> Handle receiving a user_change message when the user is not in state

- mix.exs
- mix.lock
- test/bot_test.exs
- test/integration/bot_test.exs
- test/support/fake_slack.ex
- test/support/fake_slack/router.ex
- test/support/fake_slack/websocket.ex
This adds a `Slack.FakeSlack` module that spins up a cowboy server that serves a fake [`rtm.start`](https://api.slack.com/methods/rtm.start) endpoint and a websocket interface that the bot can connect to and send/receive messages to/from.
This also adds a simple test taking advantage of the new `FakeSlack` module.
This should resolve #112
> Add fake slack and integration test simple bot

- lib/slack/lookups.ex
- lib/slack/sends.ex
- test/slack/lookups_test.exs
1. user id lookup was not checking for display_name
2. open_im_channel had a simple arity bug
> Fix two bugs related to sending message to non-existing user

- lib/slack/bot.ex
For my app, I just needed one process running for the Slack bot. For conveniences in my code I wanted to simply call `send(:slack_bot, {:message, "hello world", "#channel"})` rather than use a Registry or keep track of a pid. I think this addition would other people as it took me a bit of time to figure out naming a Slack.Bot process.
> Update bot.ex docs

- lib/slack/bot.ex
The current code generates this warning: 
`warning: String.to_char_list/1 is deprecated, use String.to_charlist/1`
So let's just swap this out, very easy to change
> switch out deprecated function

- .formatter.exs
- lib/mix/tasks/update_slack_api.exs
- lib/slack.ex
- lib/slack/bot.ex
- lib/slack/lookups.ex
- lib/slack/rtm.ex
- lib/slack/sends.ex
- lib/slack/state.ex
- lib/slack/web/documentation.ex
- lib/slack/web/web.ex
- mix.exs
- test/bot_test.exs
- test/integration/bot_test.exs
- test/slack/lookups_test.exs
- test/slack/sends_test.exs
- test/slack/state_test.exs
- test/support/fake_slack.ex
- test/support/fake_slack/router.ex
- test/support/fake_slack/websocket.ex
Elixir has a built-in autoformatter that allow us to keep codebase in one
consistent style. This should significantly improve reading and changing of code.
**Notable changes**:
* Codebase was formatted by Elixir's autoformatted
* `.formatter.exs` with initial configuration was created
> Format codebase using Elixir's autoformatter

- lib/slack/web/docs/users.lookupByEmail.json
- This adds the new (?) method on the slack api for looking up users by their email
> Add Users.lookup_by_email to Web API

- .gitignore
- README.md
- lib/slack/lookups.ex
- lib/slack/sends.ex
- test/slack/lookups_test.exs
- test/slack/sends_test.exs
> Issue# 169: Deprecate Username

- lib/slack/rtm.ex
- lib/slack/sends.ex
This was previously only supported in `Slack.Web.DefaultClient`.  This change allows SSL and other options to be used.
> Support web HTTP options with all HTTPoison requests

- .travis.yml
- mix.exs
Previously all applications were directly specified, however, `:poison` was missed. This means that if you create a release, the `:posion` would not exist. Instead switch from `:applications` to `:extra_applications` so that Elixir can build the list for us.
Requires Elixir 1.4 which was released 2.5 years ago:
https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/
Fixes #195
> Fix application list

- lib/slack/bot.ex
- lib/slack/state.ex
- test/slack/state_test.exs
Actually I wanted to work on this issue first https://github.com/BlakeWilliams/Elixir-Slack/issues/127. 
But I faced some annoying warnings so I thought why not just fix them first.
Please have a look when you have time, thank you.
- Changed`Map.size/1` to `Kernel.map_size/1`
- Changed `System.system_time(:seconds)` to `System.system_time(:second)`
- Removed unused module attribute `@since`
Hope that this is not too trivial.
> Fix some deprecated warnings

- lib/slack/web/docs/conversations.close.json
- lib/slack/web/docs/conversations.history.json
- lib/slack/web/docs/conversations.info.json
- lib/slack/web/docs/conversations.list.json
- lib/slack/web/docs/conversations.members.json
- lib/slack/web/docs/conversations.open.json
- lib/slack/web/docs/conversations.replies.json
- lib/slack/web/docs/conversations.setPurpose.json
- lib/slack/web/docs/conversations.setTopic.json
- lib/slack/web/docs/users.conversations.json
These are bot accessible (except for `set_purpose` and `set_topic`, which only work with legacy bot tokens) Conversations API definitions.
`Slack.Web.Conversations.info` in particular is useful for determining whether the arriving message was passed through direct message, group mention, private chat, or public chat, as RTM API doesn't differentiate on message types.
I've done some basic smoke tests and the endpoints seem to be returning the information I expect to see. There are some limitations on what conversations bots can operate, even if the API is exposed to bots. I've extended two descriptions beyond required minimum to indicate this.
> Add docs for bot accessible Conversation APIs

- lib/slack/web/docs/oauth.v2.access.json
- lib/slack/web/documentation.ex
- lib/slack/web/web.ex
- test/slack/web/documentation_test.exs
Docs: https://api.slack.com/methods/oauth.v2.access
This implies a breaking change: the current module generator is mapping
multi-level endpoint names to functions with [dashes in the name](https://hexdocs.pm/slack/Slack.Web.Files.html#comments/delete/3). For example,
`oauth.v2.access` becomes `Slack.Web.Oauth.v2/access/3`.
This, while valid, makes it very dificult to call the function and I believe was
unintended. This PR changes the generator so that the above endpoint becomes
`Slack.Web.Oauth.V2.access/3`.
> Adds oauth.v2.access method

- lib/slack/web/docs/users.profile.get.json
- lib/slack/web/docs/users.profile.set.json
Set: https://api.slack.com/methods/users.profile.set
Get: https://api.slack.com/methods/users.profile.get
Should probably be merged after #209 since it also generates slashed function names by default.
> Add `users.profile.get` and `users.profile.set` methods

- lib/slack/web/docs/admin.apps.approve.json
- lib/slack/web/docs/admin.apps.restrict.json
Adds the `admin.apps` methods to the documentation store:
* https://api.slack.com/methods/admin.apps.approve
* https://api.slack.com/methods/admin.apps.restrict
Note that I added in 2 additional fields (not yet used):
* `response` - providing sample output for what you would expect to get back from the API
* `warnings` - separate issues from `errors` that do not block a successful return of the request
If you're okay with this format, I'll add in an additional PR to the `documentation.ex` file to include these 2 new fields and parse them properly.
**Note that the purpose of this PR is to illustrate an updated way of handling the API methods with additional fields. Once this is approved I'd like to know if it's okay to update the remaining methods since many of them are deprecated, …
> admin.apps API Methods

- README.md
- lib/slack/web/docs/chat.scheduleMessage.json
- mix.exs
Fixes #205 via this web method:
* https://api.slack.com/methods/chat.scheduleMessage
> Adds support for scheduling messages in Slack Web API

- README.md
- mix.exs
Per `hex.publish`:
`ExDoc 0.19+ requires Elixir v1.7 and later. For earlier Elixir versions, make sure to depend on {:ex_doc, "~> 0.18.0"}`
> must set ex_doc to 0.18 for elixir 1.6

- README.md
- lib/slack/bot.ex
- lib/slack/rtm.ex
- lib/slack/sends.ex
- lib/slack/web/default_client.ex
- lib/slack/web/web.ex
- mix.exs
- test/integration/bot_test.exs
- test/slack/sends_test.exs
- test/slack/web/documentation_test.exs
- test/support/fake_slack/websocket.ex
Jason is the Elixir gold standard for JSON parsing that is actively in development, while Poison has not been updated in over 2 years. It's also faster. We need to do this because Phoenix now uses Jason and Poison does not work with `postgrex`. This is a necessary upgrade for all folks who use this app in conjunction with Phoenix 1.4+.
> [IMPORTANT] Swap Jason for Poison

- README.md
- lib/slack/web/docs/conversations.create.json
- mix.exs
`channels.create` is now [deprecated](https://api.slack.com/methods/channels.create) and will be removed in November. Instead, we need to use [`conversations.create`](https://api.slack.com/methods/conversations.create)
> Add conversations.create web API method

- README.md
- lib/slack/web/docs/chat.postEphemeral.json
- lib/slack/web/docs/chat.postMessage.json
- mix.exs
Closes #225 
Turns out the blocks optional argument was missing from 2 chat methods
https://api.slack.com/methods/chat.postMessage
https://api.slack.com/methods/chat.postEphemeral
> Add missing blocks optional argument to chat endpoints

- lib/slack/web/docs/chat.postMessage.json
https://api.slack.com/methods/chat.postMessage#arg_thread_ts `thread_ts` is a timestamp which identifies a message thread. If `thread_ts` is specified in chat.postMessage, the message is posted as a reply to the thread
Based on the the readme, I think that adding this json is all that is necessary to add this to the client, do I have that right?
> Add optional `thread_ts` param to chat.postMessage

- lib/slack/state.ex
When listening on `channel_joined` event, the code crashes before even getting to the method on [`Slack.State` ](https://github.com/BlakeWilliams/Elixir-Slack/compare/master...ashkan18:fix-channel_joined?expand=1#diff-0b063e7ff16e55ed110f157ec1ae56f5e4fbea4399e6d1d2969508fa3e495a15L48) when trying to access `channel.members`.
```
20:49:31.040 [error] ** Websocket client Slack.Bot terminating in :websocket_handle/3
for the reason :error:{:badkey, :members,
```
Looking at what `channel` is at that point, there is no `member` attribute:
```elixir
%{
reated: 1605533620,
creator: "***",
id: "***",
is_archived: false,
is_channel: true,
is_ext_shared: false,
is_frozen: false,
is_general: false,
is_group: false,
is_im: false,
is_member: true,
is_mpim: false,
is_org_shared: false, …
```
> Fix channel_joined access to channel.members
