README.md

... and the syntax of last method.
In order to be a runnable example. :)

Fix readme variable name

---

lib/slack.ex
test/slack_test.exs

Typing indicator

---

README.md

This version fixes issues with handle_info blowing up.

Update version in the Usage section

---

lib/slack.ex

Previously we were only matching on `{:ok, rtm}` which returned a
difficult to understand match error. Now, when a timeout or connection
issue causes the Rtm process to fail when starting, we return an error
the describes the problem.

Return descriptive errors when connecting fails

---

lib/slack.ex

When an exception occurs in user code happens the output is unhelpful in
diagnosing the problem since there is no stacktrace that can show where
the exception occurred.
This adds `try/rescue` blocks to `handle_message` and `handle_info`
calls so the error message and stacktrace can be printed before
re-raising to crash the genserver.

Wrap handle_* in `try/rescue`

---

lib/slack.ex

fixed a typo in the documentation

---

mix.exs

Otherwise app will not start for erlang releases

Add websocket_client to applications

---

lib/slack/lookups.ex

Fix minor typo in Lookups.lookup_channel_id documentation

---

lib/slack/web/web.ex

Because of the way HTTPoison handles multipart file uploads we have to
treat the upload API endpoint a bit differently.
This adds a workaround where we check if the name of the function is
`upload` and format the parameters for HTTPoison multipart. This works
for now, but if it changes in the future it may make sense to come up
with a more robust solution.

Add workaround for file uploads

---

lib/slack/lookups.ex

Hey Blake, thanks for all your work into this project; it has been fun playing with this!
In playing with this, I noticed that you didn't have the ability to look up a bots username so I added it.
Thanks, again!

allow bot username lookup

---

mix.exs
mix.lock

It's not much, but all the tests pass and it works with the latest versions of erlang

updates websocket_client to a newer version

---

lib/slack/web/web.ex

Addresses https://github.com/BlakeWilliams/Elixir-Slack/issues/140

Optional token params for web api

---

lib/slack/web/docs/chat.getPermalink.json

Let me know if this is a correct implementation! I needed this function for my app.

add getPermalink

---

README.md

README Update - Version Bump

---

lib/slack/state.ex
test/slack/state_test.exs

Extends the `Slack.State` to update the group topic when a change event comes in...

Update group topic

---

lib/slack/web/docs/channels.replies.json
lib/slack/web/docs/chat.postEphemeral.json
lib/slack/web/docs/groups.replies.json
lib/slack/web/docs/im.replies.json

I needed these API's, so I copy/pasted them from the docs.
I saw the discussion about these being up-to-date, but in the meantime, here's a bandaid that worked for me.
Thanks,
Anil

Add Groups.replies and Channels.replies to the web api

---

.travis.yml
lib/slack/bot.ex
lib/slack/rtm.ex
lib/slack/sends.ex
lib/slack/web/default_client.ex
lib/slack/web/web.ex
mix.exs
mix.lock

I've tried solving this issue: https://github.com/BlakeWilliams/Elixir-Slack/issues/193

193 Upgrade Poison to version 4.0.1

---

lib/slack.ex
lib/slack/bot.ex

In this PR I've added `child_spec/1` function and made Keyword acceptable in `Slack.Bot.start_link` options

More GenServer-like behaviour

---

.gitignore
lib/slack/web/docs/apps.uninstall.json
lib/slack/web/docs/auth.revoke.json

[app.uninstall](https://api.slack.com/methods/apps.uninstall)
[auth.revoke](https://api.slack.com/methods/auth.revoke)

Adds `app.uninstall` and `auth.revoke` methods.

---

README.md
lib/slack/sends.ex
mix.exs

Fixes superfluous_charset warnings

---

lib/slack/web/docs/views.open.json
lib/slack/web/docs/views.publish.json
lib/slack/web/docs/views.push.json
lib/slack/web/docs/views.update.json

Slack Web API methods for views/modals:
* https://api.slack.com/methods/views.open
* https://api.slack.com/methods/views.publish
* https://api.slack.com/methods/views.push
* https://api.slack.com/methods/views.update

Adds support for Modals/views

---

README.md
lib/slack/state.ex
mix.exs

It was crashing for me when handle user_change event and the users in Slack.State is nil.

Set default for bots,channels,groups,users,ims state

---

lib/slack/web/docs/admin.apps.approve.json
lib/slack/web/docs/admin.apps.restrict.json
lib/slack/web/docs/chat.getPermalink.json
lib/slack/web/docs/chat.scheduleMessage.json
lib/slack/web/docs/conversations.create.json
lib/slack/web/docs/conversations.invite.json
lib/slack/web/docs/views.open.json
lib/slack/web/docs/views.publish.json
lib/slack/web/docs/views.push.json
lib/slack/web/docs/views.update.json

use token from config intead of stating it as required param

---

.github/workflows/elixir.yml

This is to support running tests via github actions

Create elixir test workflow

---

README.md
lib/slack/web/docs/chat.unfurl.json
mix.exs

Provide custom unfurl behavior for user-posted URLs
refs: https://api.slack.com/methods/chat.unfurl
@acconrad please review again, thanks

Adds support for unfurls in Slack Web AP 
